name: nodejs

on: 
  push:
  gollum: 
  schedule: 
      - cron: '0 11,21 * * *'

jobs:
  one:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: npm install
      run: |
        npm install
        node index.js
        git config --local user.email "742801893@qq.com"
        git config --local user.name "zhiyi98"
        git add test.txt
        git commit -m "update test.txt"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main