name: nodejs

#=========================================================================================#
# schedule: 计划安排;  corn: 国际标准时间，北京时间+8，即下午5点钟 运行
#=========================================================================================#
on: 
  push:
  gollum: 
  schedule: 
      - cron: '0 9 * * *'

jobs:
  one:

    #=====================================================================================#
    # 运行环境：ubantu
    #=====================================================================================#

    runs-on: ubuntu-latest

    #=====================================================================================#
    # 使用 node:10 版本
    #=====================================================================================#

    steps:
    - uses: actions/checkout@v2
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    #=====================================================================================#
    # npm install
    #   操作的内容，安装node工具包、执行index.js脚本、配置git文件、操作git
    #=====================================================================================#

    - name: npm install
      run: |
        npm install
        node index.js
        git config --local user.email "742801893@qq.com"
        git config --local user.name "zhiyi98"
        git add README.md
        git commit -m "update README.md"

    #=====================================================================================#
    # Push changes
    #   最后一行github_token需要注意，这个弄了我好一会才明白，这个其实就相当于你的密码吧。这个设
    # 置方法是进入你在个人设置页面(即Settings，不是仓库里的Settings)，选择Developer settings>
    # Personal access tokens>Generate new token,设置名字为GITHUB_TOKEN,然后勾选repo,
    # admin:repo_hook,workflow等选项，最后点击Generate token即可。
    # 参考: 
    # - 运行python代码并Push到远端仓库 https://www.cnblogs.com/marsggbo/p/12090703.html
    #=====================================================================================#

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main